[package]
name = "wgas"
version = "0.1.0"
authors = ["lalanza808 <lance@lzahq.tech>"]
edition = "2018"

[dependencies]
rocket = "0.4.4"
rocket_contrib = {version = "0.4.4", features = ["tera_templates"]}
qrcode-generator = "1.0.6"
base64 = "0.12.0"
